### PR TITLE
Optimizing stinging URL, by doing it in parallel. 

### PR DESCRIPTION
**Pull request by richardleebr**
Currently, when we sting URLs, we are stinging them serially. When there are many URLs, an attack will take a long time to complete.  Let's sting in parallel.

### CODE REVIEW

**Comment by cosmin** [comment]
How about adding this as a command line flag to hit urls in parallel vs sequentially? Not sure that defaulting to parallel is always the right approach.

**Comment by richardleebr** [comment]
Cool...I'll give it a shot.

**Comment by richardleebr** [comment]
@cosmin May you please take another look 👀 ?

**Comment by richardleebr** [comment]
Thanks @astierler .  My apologies.  New PR: https://github.com/newsapps/beeswithmachineguns/pull/153

**Pull request merged**
