### PR TITLE
Allow the user to enter the content type parameter

### PR DESCRIPTION
**Pull request by kyoung**

### CODE REVIEW

**Comment by brianpatrickreavey** [comment]
Using your patch now for am XML payload.  Works great.

Two notes:
1. the parameter help text is missing a closing quote
2. the '-t' flag is already used - would recommend -P

`     attack_group.add_option('-P', '--contenttype', metavar="CONTENTTYPE", nargs=1,
                            action='store', dest='contenttype', type='string', default='text/plain',
                            help="ContentType header to send to the target of the attack.") `

**Comment by cosmin** [comment]
I can merge this if someone updates the pull request with @brianpatrickreavey's feedback

**Comment by kyoung** [comment]
Thanks @brianpatrickreavey, not sure how I missed that.

**Comment by brianpatrickreavey** [comment]
Hi @cosmin, is there anything else you needed on this?  The updates should now be in the PR.

**Pull request merged**
